// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SensorAccuracyMetrics } from "./SensorAccuracyMetrics";

/**
 * Rolling accuracy window metadata for a sensor over a time period.
 */
export type AccuracyWindow = { 
/**
 * Unix timestamp of the earliest pair in the window.
 */
window_start: bigint, 
/**
 * Unix timestamp of the latest pair in the window.
 */
window_end: bigint, 
/**
 * Computed accuracy metrics for this window.
 */
metrics: SensorAccuracyMetrics, };
