// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Air quality payload.
 */
export type AirQualityPayload = { aqi: number | null, pm25_ugm3: number | null, pm10_ugm3: number | null, o3_ppb: number | null, no2_ppb: number | null, so2_ppb: number | null, co_ppm: number | null, };
