// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality classification bands for weather data.
 *
 * Thresholds (configurable in production via `DataQualityPolicy`):
 * - High: >= 0.85
 * - Borderline: >= 0.70
 * - WarningOnly: >= 0.50
 * - Low: < 0.50
 */
export type DataQualityBand = "High" | "Borderline" | "WarningOnly" | "Low";
