// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality score for a weather observation or data submission.
 *
 * Each component is in [0.0, 1.0] where 1.0 is perfect quality.
 */
export type DataQualityScore = { 
/**
 * Overall quality score (typically a weighted combination of components).
 */
overall: number, 
/**
 * Score from range validation (are values within physical limits?).
 */
range_score: number, 
/**
 * Score from temporal/spatial consistency checks.
 */
consistency_score: number, };
