// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentalDomain } from "./EnvironmentalDomain";
import type { GeoLocation } from "./GeoLocation";
import type { ProvenanceChain } from "./ProvenanceChain";
import type { ReportPayload } from "./ReportPayload";

/**
 * A complete environmental observation report.
 *
 * # Direct construction warning
 *
 * When constructing via struct literal, the `domain` field must match the domain of
 * `payload` — use `payload.domain()` to derive it. Mismatches will cause
 * [`validate()`][EnvironmentalReport::validate] to return an error.
 * Prefer [`EnvironmentalReport::new`] which auto-derives `domain` from `payload`.
 */
export type EnvironmentalReport = { 
/**
 * Unique report identifier.
 */
report_id: string, 
/**
 * Environmental domain — must match `payload.domain()`.
 */
domain: EnvironmentalDomain, 
/**
 * Station or sensor identifier.
 */
station_id: string, 
/**
 * Geographic location of the observation.
 */
location: GeoLocation, 
/**
 * Unix timestamp when the observation was taken.
 */
observed_at: bigint, 
/**
 * Unix timestamp when the report was submitted.
 */
submitted_at: bigint, 
/**
 * Domain-specific observation data.
 */
payload: ReportPayload, 
/**
 * Optional quality score [0.0, 1.0].
 */
quality_score: number | null, 
/**
 * Optional lightweight provenance chain.
 */
provenance: ProvenanceChain | null, };
