// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Environmental observation domain.
 */
export type EnvironmentalDomain = "Weather" | "AirQuality" | "WaterQuality" | "Wildfire" | "Soil" | "Ocean" | "Hydrology";
