// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A geographic location with optional altitude.
 */
export type GeoLocation = { 
/**
 * Latitude in decimal degrees (WGS 84). Range: [-90.0, 90.0].
 */
latitude: number, 
/**
 * Longitude in decimal degrees (WGS 84). Range: [-180.0, 180.0].
 */
longitude: number, 
/**
 * Altitude above mean sea level in meters. `None` if unknown.
 */
altitude_m: number | null, };
