// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hydrology observation payload.
 */
export type HydrologyPayload = { river_discharge_m3s: number | null, water_level_m: number | null, flow_velocity_ms: number | null, sediment_load_mgl: number | null, groundwater_level_m: number | null, reservoir_storage_pct: number | null, flood_risk_level: number | null, drought_index: number | null, };
