// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ocean observation payload.
 */
export type OceanPayload = { sea_surface_temperature_c: number | null, salinity_psu: number | null, wave_height_m: number | null, wave_period_s: number | null, current_speed_ms: number | null, current_direction_deg: number | null, chlorophyll_a_mgl: number | null, dissolved_oxygen_mgl: number | null, depth_m: number | null, };
