// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configurable bounds for physics-plausibility checks on weather readings.
 *
 * Default bounds are based on observed Earth records (WMO extremes).
 */
export type PhysicsRangePolicy = { 
/**
 * Minimum plausible temperature in degrees Celsius (world record low: −89.2 °C).
 */
tempMinC: number, 
/**
 * Maximum plausible temperature in degrees Celsius (world record high: 70.7 °C).
 */
tempMaxC: number, 
/**
 * Minimum plausible barometric pressure in hPa (Typhoon Tip: 870 hPa).
 */
pressureMinHpa: number, 
/**
 * Maximum plausible barometric pressure in hPa (Siberian High: 1085 hPa).
 */
pressureMaxHpa: number, 
/**
 * Minimum relative humidity in percent.
 */
humidityMinPct: number, 
/**
 * Maximum relative humidity in percent.
 */
humidityMaxPct: number, 
/**
 * Maximum plausible wind speed in m/s (world record gust: 113.3 m/s).
 */
windSpeedMaxMs: number, 
/**
 * Maximum physically plausible temperature rate of change in °C per minute.
 */
tempRateMaxCPerMin: number, };
