// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A physics violation detected during weather reading validation.
 *
 * Serialized as an internally tagged union with `"type"` as the discriminator,
 * matching the TypeScript discriminated union pattern.
 */
export type PhysicsViolation = { "type": "TemperatureOutOfRange", valueC: number, min: number, max: number, } | { "type": "PressureOutOfRange", valueHpa: number, min: number, max: number, } | { "type": "HumidityOutOfRange", valuePct: number, min: number, max: number, } | { "type": "WindSpeedExceedsMaximum", valueMs: number, max: number, } | { "type": "TemperatureRateExceeded", deltaC: number, limit: number, } | { "type": "CrossParameterInconsistency", detail: string, };
