// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single provenance attestation step.
 */
export type ProvenanceEntry = { attester_id: string, timestamp: bigint, };
