// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvenanceEntry } from "./ProvenanceEntry";

/**
 * Lightweight provenance chain: ordered list of attestation entries.
 */
export type ProvenanceChain = Array<ProvenanceEntry>;
