// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirQualityPayload } from "./AirQualityPayload";
import type { HydrologyPayload } from "./HydrologyPayload";
import type { OceanPayload } from "./OceanPayload";
import type { SoilPayload } from "./SoilPayload";
import type { WaterQualityPayload } from "./WaterQualityPayload";
import type { WeatherObservation } from "./WeatherObservation";
import type { WildfirePayload } from "./WildfirePayload";

/**
 * Tagged union of all environmental domain payloads.
 */
export type ReportPayload = { "domain": "Weather", "data": WeatherObservation } | { "domain": "AirQuality", "data": AirQualityPayload } | { "domain": "WaterQuality", "data": WaterQualityPayload } | { "domain": "Wildfire", "data": WildfirePayload } | { "domain": "Soil", "data": SoilPayload } | { "domain": "Ocean", "data": OceanPayload } | { "domain": "Hydrology", "data": HydrologyPayload };
