// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single sensor reading paired with a reference (ground truth) value.
 */
export type SensorReferencePair = { 
/**
 * Value reported by the IoT sensor.
 */
sensor_value: number, 
/**
 * Reference value from an official station or consensus.
 */
reference_value: number, };
