// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of sensor accuracy for reward calculation.
 *
 * Thresholds: Excellent >= 0.90, Good >= 0.75, Marginal >= 0.50, Poor < 0.50.
 */
export type SensorAccuracyBand = "Excellent" | "Good" | "Marginal" | "Poor";
