// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accuracy metrics for an IoT sensor compared against reference observations.
 *
 * All error metrics use the same units as the underlying measurement (e.g.,
 * degrees C for temperature sensors, hPa for pressure sensors).
 */
export type SensorAccuracyMetrics = { 
/**
 * Mean Absolute Error. Non-negative.
 */
mae: number, 
/**
 * Root Mean Squared Error. Non-negative.
 */
rmse: number, 
/**
 * Mean signed bias (sensor - reference). Positive means sensor reads high.
 */
bias: number, 
/**
 * Pearson correlation coefficient. In \[-1.0, 1.0\].
 */
correlation: number, 
/**
 * Number of comparison pairs used to compute these metrics.
 */
sample_count: number, 
/**
 * Composite accuracy score in \[0.0, 1.0\] where 1.0 is perfect.
 */
accuracy_score: number, };
