// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Soil observation payload.
 */
export type SoilPayload = { moisture_pct: number | null, temperature_c: number | null, ph: number | null, organic_carbon_pct: number | null, nitrogen_mgl: number | null, phosphorus_mgl: number | null, potassium_mgl: number | null, conductivity_dsm: number | null, depth_cm: number | null, };
