// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A minimal weather reading used as input for physics validation.
 *
 * Separate from [`crate::WeatherObservation`] — this carries only the subset of
 * fields needed for physics range-checking plus a timestamp.
 */
export type ValidationReading = { 
/**
 * Air temperature in degrees Celsius.
 */
temperatureC: number | null, 
/**
 * Atmospheric pressure in hectopascals (hPa).
 */
pressureHpa: number | null, 
/**
 * Relative humidity as a percentage [0, 100].
 */
humidityPct: number | null, 
/**
 * Wind speed in meters per second.
 */
windSpeedMs: number | null, 
/**
 * Unix timestamp of the reading (seconds since epoch).
 */
timestampUnix: number, };
