// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Water quality payload.
 */
export type WaterQualityPayload = { ph: number | null, dissolved_oxygen_mgl: number | null, turbidity_ntu: number | null, conductivity_usm: number | null, temperature_c: number | null, total_dissolved_solids_mgl: number | null, };
