// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A weather observation with standard meteorological variables.
 *
 * All fields are optional — sensors may not report every variable.
 * Units follow SI / WMO conventions.
 */
export type WeatherObservation = { 
/**
 * Air temperature in degrees Celsius.
 */
temperature_c: number | null, 
/**
 * Relative humidity as a percentage [0, 100].
 */
humidity_percent: number | null, 
/**
 * Atmospheric pressure in hectopascals (hPa / mbar).
 */
pressure_hpa: number | null, 
/**
 * Wind speed in meters per second.
 */
wind_speed_ms: number | null, 
/**
 * Wind direction in degrees [0, 360). 0 = North, 90 = East.
 */
wind_direction_deg: number | null, 
/**
 * Precipitation accumulation in millimeters.
 */
precipitation_mm: number | null, 
/**
 * Dewpoint temperature in degrees Celsius.
 */
dewpoint_c: number | null, 
/**
 * Horizontal visibility in meters.
 */
visibility_m: number | null, };
