// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wildfire observation payload.
 */
export type WildfirePayload = { fire_radiative_power_mw: number | null, burn_area_km2: number | null, confidence_pct: number | null, smoke_aod: number | null, containment_pct: number | null, active: boolean | null, };
